apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-object-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: x1-community
      app.kubernetes.io/instance: x1-community
      app.kubernetes.io/component: image-object-detection
  template:
    metadata:
      labels:
        app.kubernetes.io/name: x1-community
        app.kubernetes.io/instance: x1-community
        app.kubernetes.io/component: image-object-detection
    spec:
      nodeSelector:
        dedicated: app
      imagePullSecrets:
        - name: basicai-registry
      containers:
        - name: image-object-detection
          image: $IMAGE_OBJECT_DETECTION_IMAGE_NAME:$CI_COMMIT_SHORT_SHA
          resources:
            requests:
              memory: 400Mi
              cpu: 200m
            limits:
              memory: 4Gi
              cpu: 2
          ports:
            - name: http
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: image-object-detection
spec:
  selector:
    app.kubernetes.io/name: x1-community
    app.kubernetes.io/instance: x1-community
    app.kubernetes.io/component: image-object-detection
  ports:
    - name: http
      port: 80
      targetPort: 5000
