version: '3.9'
services:
  nginx:
    image: nginx:1.22
    environment:
      MYSQL_ROOT_PASSWORD: ImOxO8Lz
      MYSQL_DATABASE: x1_community
      MYSQL_USER: x1_community
      MYSQL_PASSWORD: Rc4K3L6f
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ImOxO8Lz
      MYSQL_DATABASE: x1_community
      MYSQL_USER: x1_community
      MYSQL_PASSWORD: Rc4K3L6f
    ports:
      - 8081:3306
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:6.2
    ports:
      - 8082:6379
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1tQB970y
    ports:
      - 8083:9000
      - 8084:9001
    volumes:
      - minio-data:/data
  backend:
    build: ./backend
    image: backend
    environment:
      # Override configs in application.yml.
      X1_DEBUG: false
      # X1_SPRING_DATASOURCE_URL:
      # X1_SPRING_DATASOURCE_USERNAME:
      # X1_SPRING_DATASOURCE_PASSWORD:
      # X1_SPRING_REDIS_HOST:
      # X1_SPRING_REDIS_PORT:
      # X1_SPRING_REDIS_PASSWORD:
      # X1_MINIO_ENDPOINT:
      # X1_MINIO_ACCESSKEY:
      # X1_MINIO_SECRETKEY:
      # X1_MINIO_BUCKETNAME:
    ports:
      - 8180:8080
    # volumes:
    # Using customized application.yml to override default file in image.
    #   - /host/path/to/customized/application.yml:/app/config/application.yml
    depends_on:
      - mysql
      - redis
volumes:
  mysql-data:
  redis-data:
  minio-data:
