version: '3.9'
services:
  nginx:
    image: nginx:1.22
    environment:
      MYSQL_ROOT_PASSWORD: ImOxO8Lz
      MYSQL_DATABASE: x1_community
      MYSQL_USER: x1_community
      MYSQL_PASSWORD: Rc4K3L6f
    ports:
      - 8190:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ImOxO8Lz
      MYSQL_DATABASE: x1_community
      MYSQL_USER: x1_community
      MYSQL_PASSWORD: Rc4K3L6f
    ports:
      - 8191:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d
  redis:
    image: redis:6.2
    ports:
      - 8192:6379
    volumes:
      - redis-data:/data
  minio:
    image: minio/minio:RELEASE.2022-08-25T07-17-05Z
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: 1tQB970y
    ports:
      - 8193:9000
      - 8194:9001
    volumes:
      - minio-data:/data
  backend:
    build: ./backend
    ports:
      - 8180:8080
    # volumes:
    # Using customized application.yml to override default configs.
    #   - /host/path/to/customized/application.yml:/app/config/application.yml
    depends_on:
      - mysql
      - redis
  frontend:
    build: ./frontend
    ports:
      - 8181:8080
volumes:
  mysql-data:
  redis-data:
  minio-data:
