stages:
  - build-package
  - build-image
  - deploy

variables:
  APP_NAME: "x1-community"
  APP_VERSION: "0.5"

  FRONTEND_PACKAGE_DIR: "dist"
  BACKEND_PACKAGE_NAME: "${APP_NAME}-backend-${APP_VERSION}-SNAPSHOT.jar"

  FRONTEND_IMAGE_NAME: "registry.talos.basic.ai/basicai/${APP_NAME}/frontend"
  BACKEND_IMAGE_NAME: "registry.talos.basic.ai/basicai/${APP_NAME}/backend"
  IMAGE_OBJECT_DETECTION_IMAGE_NAME: "registry.talos.basic.ai/basicai/${APP_NAME}/image-object-detection"

  DOCKER_HUB_FRONTEND_IMAGE_NAME: "basicai/${APP_NAME}-frontend"
  DOCKER_HUB_BACKEND_IMAGE_NAME: "basicai/${APP_NAME}-backend"
  DOCKER_HUB_IMAGE_OBJECT_DETECTION_IMAGE_NAME: "basicai/${APP_NAME}-image-object-detection"

  KUBERNETES_NAMESPACE: "x1-community"

build-frontend-package:
  stage: build-package
  tags:
    - nodejs-16
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - frontend/*
        - frontend/**/*
  script:
    - cd frontend/main
    - npm install
    - npm run build
    # - cd ../image-tool
    # - npm install
    # - npm run build
    - cd ../pc-tool
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/$FRONTEND_PACKAGE_DIR
  cache:
    paths:
      - frontend/main/node_modules
      - frontend/image-tool/node_modules
      - frontend/pc-tool/node_modules

build-backend-package:
  stage: build-package
  tags:
    - openjdk-11
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - backend/*
        - backend/**/*
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/backend/.m2/repository"
    MAVEN_ARGS: "--batch-mode"
  script:
    - cd backend
    - mvn $MAVEN_ARGS package
  artifacts:
    paths:
      - backend/target/$BACKEND_PACKAGE_NAME
  cache:
    paths:
      - backend/.m2/repository

build-deploy-package:
  stage: build-package
  tags:
    - ubuntu
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - deploy/*
        - deploy/**/*
        - docker-compose.yml
  variables:
    DEPLOY_PACKAGE_NAME: "${APP_NAME}-${APP_VERSION}-${CI_COMMIT_REF_NAME}.tar.gz"
  script:
    - tar zcvf $DEPLOY_PACKAGE_NAME --transform 's,^,'"$APP_NAME"'/,' deploy docker-compose.yml
  artifacts:
    paths:
      - $DEPLOY_PACKAGE_NAME

.build-image:
  stage: build-image
  tags:
    - docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  services:
    - docker:20-dind
  before_script:
    - until docker info; do sleep 1; done
    - echo "$BASICAI_REGISTRY_PASS" | docker login $BASICAI_REGISTRY --username $BASICAI_REGISTRY_USER --password-stdin
    - echo "$DOCKER_HUB_REGISTRY_PASS" | docker login --username $DOCKER_HUB_REGISTRY_USER --password-stdin
  after_script:
    - cd $WORKING_DIR
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from $IMAGE_NAME:latest -t $IMAGE_NAME:$CI_COMMIT_REF_NAME -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
    # Push main and tag image to Docker Hub.
    - if [[ $CI_COMMIT_REF_NAME == main ]]; then docker tag $IMAGE_NAME:$CI_COMMIT_REF_NAME $DOCKER_HUB_IMAGE_NAME:latest; docker push $DOCKER_HUB_IMAGE_NAME:latest; fi
    - if [[ $CI_COMMIT_REF_NAME == v* ]]; then docker tag $IMAGE_NAME:$CI_COMMIT_REF_NAME $DOCKER_HUB_IMAGE_NAME:$CI_COMMIT_REF_NAME; docker push $DOCKER_HUB_IMAGE_NAME:$CI_COMMIT_REF_NAME; fi

build-backend-image:
  extends: .build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - .ops/backend.*
        - backend/*
        - backend/**/*
  variables:
    WORKING_DIR: backend
    IMAGE_NAME: $BACKEND_IMAGE_NAME
    DOCKER_HUB_IMAGE_NAME: $DOCKER_HUB_BACKEND_IMAGE_NAME
  script:
    - cd $WORKING_DIR
    - cp ../.ops/backend.dockerfile ./Dockerfile
    - cp ../.ops/backend.dockerignore ./.dockerignore
    - sed -i 's/$BACKEND_PACKAGE_NAME/'"$BACKEND_PACKAGE_NAME"'/g' Dockerfile

build-frontend-image:
  extends: .build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - .ops/frontend.*
        - frontend/*
        - frontend/**/*
  variables:
    WORKING_DIR: frontend
    IMAGE_NAME: $FRONTEND_IMAGE_NAME
    DOCKER_HUB_IMAGE_NAME: $DOCKER_HUB_FRONTEND_IMAGE_NAME
  script:
    - cd $WORKING_DIR
    - cp ../.ops/frontend.dockerfile ./Dockerfile
    - cp ../.ops/frontend.dockerignore ./.dockerignore
    - sed -i 's/$FRONTEND_PACKAGE_DIR/'"$FRONTEND_PACKAGE_DIR"'/g' Dockerfile

build-image-object-detection-image:
  extends: .build-image
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG =~ /^v/
      changes:
        - .ops/image-object-detection.*
        - model/image-object-detection/*
        - model/image-object-detection/**/*
  variables:
    WORKING_DIR: model/image-object-detection
    IMAGE_NAME: $IMAGE_OBJECT_DETECTION_IMAGE_NAME
    DOCKER_HUB_IMAGE_NAME: $DOCKER_HUB_IMAGE_OBJECT_DETECTION_IMAGE_NAME
  script:
    - cd $WORKING_DIR
    - cp ../../.ops/image-object-detection.dockerfile ./Dockerfile
    - cp ../../.ops/image-object-detection.dockerignore ./.dockerignore

.deploy:
  stage: deploy
  tags:
    - kubectl
  before_script:
    - cd .ops/$ENV
    - sed -i 's/$APP_NAME/'"$APP_NAME"'/g' $DEPLOYMENT
    - sed -i 's/$APP_VERSION/'"$APP_VERSION"'/g' $DEPLOYMENT
    - sed -i 's/$CI_COMMIT_SHORT_SHA/'"$CI_COMMIT_SHORT_SHA"'/g' $DEPLOYMENT

deploy-backend-to-alidev:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alidev/backend-*
        - backend/*
        - backend/**/*
  variables:
    ENV: alidev
    DEPLOYMENT: backend-deployment.yml
  script:
    - sed -i 's|$BACKEND_IMAGE_NAME|'"$BACKEND_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_DEVELOPMENT

deploy-frontend-to-alidev:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alidev/frontend-*
        - frontend/*
        - frontend/**/*
  variables:
    ENV: alidev
    DEPLOYMENT: frontend-deployment.yml
  script:
    - sed -i 's|$FRONTEND_IMAGE_NAME|'"$FRONTEND_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_DEVELOPMENT

deploy-image-object-detection-to-alidev:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alidev/image-object-detection-*
        - model/image-object-detection/*
        - model/image-object-detection/**/*
  variables:
    ENV: alidev
    DEPLOYMENT: image-object-detection-deployment.yml
  script:
    - sed -i 's|$IMAGE_OBJECT_DETECTION_IMAGE_NAME|'"$IMAGE_OBJECT_DETECTION_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_DEVELOPMENT

deploy-backend-to-alitest:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alitest/backend-*
        - backend/*
        - backend/**/*
  when: manual
  variables:
    ENV: alitest
    DEPLOYMENT: backend-deployment.yml
  script:
    - sed -i 's|$BACKEND_IMAGE_NAME|'"$BACKEND_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_TESTING

deploy-frontend-to-alitest:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alitest/frontend-*
        - frontend/*
        - frontend/**/*
  when: manual
  variables:
    ENV: alitest
    DEPLOYMENT: frontend-deployment.yml
  script:
    - sed -i 's|$FRONTEND_IMAGE_NAME|'"$FRONTEND_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_TESTING

deploy-image-object-detection-to-alitest:
  extends: .deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
        - .ops/alitest/image-object-detection-*
        - model/image-object-detection/*
        - model/image-object-detection/**/*
  when: manual
  variables:
    ENV: alitest
    DEPLOYMENT: image-object-detection-deployment.yml
  script:
    - sed -i 's|$IMAGE_OBJECT_DETECTION_IMAGE_NAME|'"$IMAGE_OBJECT_DETECTION_IMAGE_NAME"'|g' $DEPLOYMENT
    - kubectl apply -f $DEPLOYMENT -n $KUBERNETES_NAMESPACE --kubeconfig=$KUBECONFIG_ALIYUN_TESTING
